### ISSUE TITLE
Nothing Pushed

### ISSUE THREAD

**Issue by Smithx10** [autopilotpattern/postgres#2]
@misterbisson, I was thinking to start working on this for work / pleasure.   Do you by chance have anything?

**Comment by misterbisson** [comment]
@Smithx10 I'm not aware of any work that's gone farther than idle conversation. I'd love to work with you if you're looking for a project.

**Comment by Smithx10** [comment]
@misterbisson  I was heavily inspired by the way that Manatee works.  It's a shame that we can't delegate datasets in the current docker on triton implementation.   Would it be possible to expose that functionality for on-prem triton users?   I understand the risks of not implementing it the JPC in regards to zfs recv.   Do you think that topology is the desired configuration for the APP?   What are your thoughts?    https://github.com/joyent/manatee/blob/master/docs/user-guide.md   I have  Manta running on prem, but believe we should support nfs target backup targets as well.

**Comment by yosifkit** [comment]
@moghedrin and I were in the middle of refactoring the backup functionality in the mysql pattern and wanted to finish it so that more of the code can be reused here.  We won't say no to more help to get this pattern off the ground though.

Current WIP for the backup generalization is in https://github.com/infosiftr/autopilotpattern-mysql/tree/generalize-backup. Feel free to make any suggestion there that'll help it work for PostgreSQL too! (or if you have any questions).

**Comment by misterbisson** [comment]
[ZFS datasets can be delegated to an instance](https://docs.joyent.com/private-cloud/instances/delegated-data-sets), though it is [not safe to delegate datasets to untrusted users](https://github.com/joyent/rfd/blob/master/rfd/0044/README.md#safety-considerations). [RFD36 discusses some solutions that would help](https://github.com/joyent/rfd/tree/master/rfd/0036#desirable-features-not-addressed-in-this-rfd), but the only way to do this today is the pattern demonstrated in [autopilotpattern/mysql](https://github.com/autopilotpattern/mysql).

**Comment by Smithx10** [comment]
Everyone,

Should we add connection handling with pgbouncer etc?

**Comment by misterbisson** [comment]
Please see initial implementation in https://github.com/autopilotpattern/postgres/pull/3
